#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, sorted from
# the greatest to the lowest number of occurrences
awk '$9 ~ /^[0-9]+$/ {print $1, $9}' "${1:-apache-access.log}" | sort | uniq -c | sort -rn | awk '{print $1, $2, $3}'
