#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, printing
# "I am invincible!!!" when it receives a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done
